'added'

diff --git a/.github/workflows/auto-comment-pr-raise.yml b/.github/workflows/auto-comment-pr-raise.yml
--- a/.github/workflows/auto-comment-pr-raise.yml
+++ b/.github/workflows/auto-comment-pr-raise.yml
@@ -13,25 +13,24 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Add Comment to Pull Request
-      run: |
-        COMMENT=$(cat <<EOF
-        {
-          "body": "@${{ github.actor }}  <h3>Welcome to the Project!</h3> Thank you for opening a <strong>Pull Request 🙌</strong>! We’re thrilled to have you join us for <strong>Hacktoberfest 💖</strong>.
-We’ll review your submission and get back to you shortly. Thanks for contributing!"
-        }
-        EOF
-        )
-        RESPONSE=$(curl -s -o response.json -w "%{http_code}" \
-          -X POST \
-          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
-          -H "Accept: application/vnd.github.v3+json" \
-          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
-          -d "$COMMENT")
-        cat response.json
-        if [ "$RESPONSE" -ne 201 ]; then
-          echo "Failed to add comment"
-          exit 1
-        fi
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Add Comment to Pull Request
+        run: |
+          COMMENT=$(cat <<EOF
+          {
+            "body": "@${{ github.actor }} <h3>Welcome to the Project!</h3> Thank you for opening a <strong>Pull Request 🙌</strong>! We’re thrilled to have you join us for <strong>Hacktoberfest 💖</strong>. We’ll review your submission and get back to you shortly. Thanks for contributing!"
+          }
+          EOF
+          )
+          RESPONSE=$(curl -s -o response.json -w "%{http_code}" \
+            -X POST \
+            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+            -H "Accept: application/vnd.github.v3+json" \
+            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
+            -d "$COMMENT")
+          cat response.json
+          if [ "$RESPONSE" -ne 201 ]; then
+            echo "Failed to add comment"
+            exit 1
+          fi
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
